version: '3.8'  # Use the appropriate Docker Compose version

services:
  camunda-app:
    container_name: camunda-app
    image: mangoket/camunda-app
    ports:
      - "9004:9004"
    networks:
      - camunda-network
    volumes:
      - /srv/docker-logs/$LOG_FOLDER:/logs

networks:
  camunda-network:
    driver: bridge